# Generated by Django 5.2.6 on 2026-09-22 22:58

#importacoes
import django.db.models.deletion
from django.db import migrations, models


#-------------------------------------------------------------------------------------

#migracao do banco de dados
class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0004_autenticacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='%(class)s_perfil', to='elo.usuario'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='%(class)s_perfil', to='elo.usuario'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='%(class)s_perfil', to='elo.usuario'),
        ),
    ]
#-------------------------------------------------------------------------------------
