# Generated by Django 5.2.6 on 2026-09-22 23:22

#importacoes
from django.db import migrations, models


#-------------------------------------------------------------------------------------

#migracao do banco de dados
class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0005_alter_aluno_usuario_alter_professor_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=64, unique=True)),
                ('falhas', models.PositiveIntegerField(default=0)),
                ('inicio', models.DateTimeField()),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'limite_login',
            },
        ),
    ]
#-------------------------------------------------------------------------------------
