# Generated by Django 5.2.6 on 2026-09-22 23:48

#importacoes
from django.db import migrations, models


#-------------------------------------------------------------------------------------

#migracao do banco de dados
class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0006_limitelogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('autor_id_original', models.PositiveBigIntegerField(blank=True, null=True)),
                ('autor', models.CharField(max_length=150)),
                ('acao', models.CharField(choices=[('LOGIN', 'Entrada no sistema'), ('SAIDA', 'Saída do sistema'), ('FALHA_LOGIN', 'Falha no login'), ('BLOQUEIO_LOGIN', 'Login bloqueado'), ('ACESSO_NEGADO', 'Acesso negado'), (
                    'CRIACAO', 'Cadastro criado'), ('EDICAO', 'Cadastro alterado'), ('EXCLUSAO', 'Cadastro excluído'), ('PERMISSAO', 'Permissão definida ou alterada'), ('SENHA', 'Senha definida ou redefinida')], db_index=True, max_length=25)),
                ('entidade', models.CharField(blank=True, max_length=80)),
                ('objeto_id', models.CharField(blank=True, max_length=64)),
                ('detalhes', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'db_table': 'registro_auditoria',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
    ]
#-------------------------------------------------------------------------------------
