# Generated by Django 6.1.1 on 2026-09-25 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0009_troca_senha_obrigatoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConexaoGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidade', models.CharField(max_length=64)),
                ('credenciais', models.TextField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conexao_google', to='elo.usuario')),
            ],
            options={
                'db_table': 'conexao_google',
            },
        ),
        migrations.CreateModel(
            name='SincronizacaoGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidade', models.CharField(max_length=64)),
                ('evento_id', models.CharField(max_length=128)),
                ('sincronizado_em', models.DateTimeField(blank=True, null=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elo.atividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elo.usuario')),
            ],
            options={
                'db_table': 'sincronizacao_google',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'atividade', 'identidade'), name='google_evento_usuario_atividade')],
            },
        ),
    ]
